# Generated by Django 4.2.3 on 2023-07-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sotish uchun Kategoriya',
                'verbose_name_plural': 'Sotish uchun Kategoriyalar',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sotilgan maxsulot uchun kategoriya',
                'verbose_name_plural': 'Sotilgan maxsulotlar uchun  kategoriyalar',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Commentlar',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Biz haqimizda ma'lumot ",
                'verbose_name_plural': "Biz haqimizda ma'lumotlar",
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='partner_photo/%Y/%m/%d/', verbose_name='Hamkor rasmi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'statistika',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='team_photo/%Y/%m/%d/', verbose_name="jamoa a'zosining rasmi")),
                ('number', models.CharField(max_length=15, verbose_name="jamoa a'xosining raqami")),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='2product_photo/%Y/%m/%d/', verbose_name='Maxsulot rasmi')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1_category2', to='newapp.category2', verbose_name='Sotilgan maxsulot kategoriyasi')),
            ],
            options={
                'verbose_name': 'Sotilgan maxsulot uchun kategoriya',
                'verbose_name_plural': 'Sotilgan maxsulotlar uchun  kategoriyalar',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='1product_photo/%Y/%m/%d/', verbose_name='Maxsulot rasmi')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1_category1', to='newapp.category1', verbose_name='Sotish uchun maxsulot kategoriyasi')),
            ],
            options={
                'verbose_name': 'Sotish uchun maxsulot kategoriyasi',
                'verbose_name_plural': 'Sotish uchun maxsulot kategoriyasi',
                'ordering': ('-created_at', 'status'),
            },
        ),
    ]
