# Generated by Django 4.2.3 on 2023-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category1',
            options={'ordering': ('-created_at', 'status'), 'verbose_name': 'Mahsulot sotish uchun Kategoriya', 'verbose_name_plural': 'Sotish uchun Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='category2',
            options={'ordering': ('-created_at', 'status'), 'verbose_name': 'Sotilgan maxsulotlar uchun kategoriya', 'verbose_name_plural': 'Sotilgan maxsulotlar uchun  kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='product1',
            options={'ordering': ('-created_at', 'status'), 'verbose_name': 'Sotish uchun maxsulot ', 'verbose_name_plural': 'Sotish uchun maxsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='product2',
            options={'ordering': ('-created_at', 'status'), 'verbose_name': 'Sotilgan maxsulot ', 'verbose_name_plural': 'Sotilgan maxsulotlar'},
        ),
    ]
